# Copied from https://github.com/rerun-io/rerun_template
on:
  push:
    branches:
      - "main"
  pull_request:
    types: [ opened, synchronize ]

name: C++

jobs:
  cpp-check:
    name: "C++ build"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.41.4
          cache: true

      - run: pixi run build

      - run: pixi run cpp-fmt-check
